name 'raspi'
maintainer 'Ranjib Dey'
maintainer_email 'ranjib@linux.com'
version '0.0.1'
depends 'packagecloud'
depends 'sudo'
depends 'openssh'
depends 'apparmor'
depends 'omnibus'
depends 'systemd'
